### ISSUE TITLE
Allow passing directly vars instead of env keys

### ISSUE THREAD

**Issue by mping** [heroku/env-keystore#11]
Title says it all. Basically make the constructors `public`.

**Comment by jkutner** [comment]
it's not really *env* keystore any more then is it :) i understand why this would be useful though. 

can you tell me more about your use case? where do the values come from if not env vars?

**Comment by mping** [comment]
Hehe you're right. I'm using clojure and have a unified property loader (properties can come from env, from a file, from cmdline args and so on) and I'd like to use different certs for different environments and change them on the fly.

Right now I have a class that extends `EnvKeyStore` and exposes the methods that allow passing the values directly, but it's basically a hack.

**Comment by mping** [comment]
@jkutner sure! Thanks!

**Comment by jkutner** [comment]
ok, it might be a little while before I get to that, but I'd definitely accept a PR if you want to give it a stab.

**Comment by jkutner** [comment]
Fixed by #12
