### ISSUE TITLE
Create keystore without cert

### ISSUE THREAD

**Issue by jkutner** [heroku/env-keystore#2]
`EnvKeyStore` should be able to create a keystore file without a certificate. This would be analogous to a command like:

```
keytool -genkeypair -alias pac4j-demo -keypass pac4j-demo-passwd -keystore samlKeystore.jks -storepass pac4j-demo-passwd -keyalg RSA -keysize 2048 -validity 3650
```

This is derived from the example in the [pac4j documentation](http://www.pac4j.org/docs/clients/saml.html).

**Comment by Malax** [comment]
Closing since this is an old issue without any traction currently. If a user of this library needs this functionality, please comment here or open a new issue.
