### ISSUE TITLE
Create a keystore from a string

### ISSUE THREAD

**Issue by codepope** [heroku/env-keystore#3]
I have certificates coming off Cloud Foundry JSON/env variables so they need lots of pre-processing. 

Rather than make a fork which did the pre-processing, would it be reasonable to make the  EnvKeyStore(String key, String cert, String password) and  EnvKeyStore(String cert, String password) methods explicitly public? 

(Or am I missing something that mitigates against doing that?)

**Comment by jkutner** [comment]
How about a `public static createFromStrings(String key, String cert, String password)` or similar? I want the default to be env var names, and I don't want to confuse folks with multiple options that seem identical both take Strings.

**Comment by codepope** [comment]
Sounds like a great alternative.

**Comment by dhoepelman** [comment]
Ran into the same issue, would prefer to pass strings to ease local development and test code.

**Comment by jkutner** [comment]
@dhoepelman how does the `createFromStrings` method sound to you? Let me know if you have any suggestions to help disambiguate env var names from values.

**Comment by dhoepelman** [comment]
@jkutner `createFromStrings` is fine. Maybe `createFromPEMStrings` or something for clarity if that's your concern.

Currently, we're accessing the private constructor with reflection, so anything is better.

**Comment by jkutner** [comment]
Fixed by 2df25de5bd4139112115336a0d38c681eef50c66
