### ISSUE TITLE
Allow ability to append cacerts to TrustStore

### ISSUE THREAD

**Issue by ml-sfdc** [heroku/env-keystore#9]
As we create a new TrustStore, it overrides Java's default TrustStore which already has loaded all cacerts on the system. Because of this, it makes it difficult to validate different destinations with differing signers. Would like the ability to create a TrustStore which copies over the existing cacerts and appends the one from the ENV var.

**Comment by jkutner** [comment]
@ml-sfdc how does #10 look?

**Comment by ml-sfdc** [comment]
Thanks @jkutner! 

@holtonma - Would you like to give it a go?

**Comment by holtonma** [comment]
@ml-sfdc @jkutner 
Awesome, will review this afternoon.
Have a few things on my plate next few days, but we can pull it in and test it early 216.  Many thanks, @jkutner 🍻

**Comment by jkutner** [comment]
@holtonma @ml-sfdc if it helps, I can cut a release (because this new method is basically orthogonal to existing methods). Then we can iterate if it doesn't work for you.
